apiVersion: v1
kind: Pod
metadata:
  name: tpu-mock-test-pod
spec:
  nodeSelector:
    cloud.google.com/gke-tpu-mock: tpu7x
    cloud.google.com/gke-tpu-accelerator: tpu7x
    cloud.google.com/gke-tpu-topology: 4x4x4
  containers:
  - name: sheep-counter
    image: busybox
    command: ["/bin/sh", "-c", "i=0; while true; do echo \"Sheep count: $i\"; i=$((i+1)); sleep 20; done"]
    resources:
      limits:
        google.com/tpu: "4"
      requests:
        google.com/tpu: "4"
