apiVersion: v1
kind: Pod
metadata:
  name: tpu-mock-test-pod
spec:
  nodeName: gke-taohe-gpu-t2-pool-1-b5cfc725-smnc
  nodeSelector:
    cloud.google.com/gke-tpu-accelerator: tpu-v4-podslice
    cloud.google.com/gke-tpu-topology: 2x2x1
  containers:
  - name: sheep-counter
    image: busybox
    command: ["/bin/sh", "-c", "i=0; while true; do echo \"Sheep count: $i\"; i=$((i+1)); sleep 20; done"]
    resources:
      limits:
        google.com/tpu: "4"
      requests:
        google.com/tpu: "4"
